name: flows
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=>3
  - tqdm
  - colorama
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pytorch::pytorch=>1.6
  - conda-forge::hydra-core
  - conda-forge::jupyterlab
  - yapf
  - mypy
  - flake8
