network:
  - name: realnvp
  - layers: 32

train:
  - steps: 100000
  - samples: 1024

run:
  - distrib: circles
  - ckpt_path: null
  - output: outputs
  - display: 1

defaults:
  - network: realnvp
